/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Achievements */
        get: operations["get_achievements_api_achievements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Phases */
        get: operations["list_phases_api_phases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phases/{phase_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Phase Tasks */
        get: operations["list_phase_tasks_api_phases__phase_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Flashcards */
        get: operations["list_flashcards_api_flashcards_get"];
        put?: never;
        /** Create Flashcard */
        post: operations["create_flashcard_api_flashcards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flashcards/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Due */
        get: operations["list_due_api_flashcards_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flashcards/intro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Intro */
        get: operations["list_intro_api_flashcards_intro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flashcards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Flashcard */
        delete: operations["delete_flashcard_api_flashcards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Flashcard */
        patch: operations["update_flashcard_api_flashcards__card_id__patch"];
        trace?: never;
    };
    "/api/flashcards/{card_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Flashcard */
        post: operations["review_flashcard_api_flashcards__card_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flashcards/{card_id}/intro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Introduce Flashcard */
        post: operations["introduce_flashcard_api_flashcards__card_id__intro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_api_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_api_questions__question_id__delete"];
        options?: never;
        head?: never;
        /** Update Question */
        patch: operations["update_question_api_questions__question_id__patch"];
        trace?: never;
    };
    "/api/questions/{question_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Attempts */
        get: operations["list_attempts_api_questions__question_id__attempts_get"];
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt_api_questions__question_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resources */
        get: operations["list_resources_api_resources_get"];
        put?: never;
        /** Create Resource */
        post: operations["create_resource_api_resources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Resource */
        delete: operations["delete_resource_api_resources__resource_id__delete"];
        options?: never;
        head?: never;
        /** Update Resource */
        patch: operations["update_resource_api_resources__resource_id__patch"];
        trace?: never;
    };
    "/api/journal/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Streak */
        get: operations["get_streak_api_journal_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_api_journal_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_journal_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Days */
        get: operations["get_days_api_journal_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journal/days/{day}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Day Note
         * @description Notatka do dnia nauki. Pusta treść kasuje notatkę.
         */
        put: operations["put_day_note_api_journal_days__day__note_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today
         * @description Plan sesji dnia. Nie zapisuje nic - każdy krok odkłada się osobnym endpointem.
         *
         *     Dzięki temu sesja przerwana w połowie nie gubi zrobionej pracy i nie
         *     zostawia stanu do posprzątania: nie ma czego wznawiać, bo plan wystarczy
         *     policzyć od nowa.
         */
        get: operations["get_today_api_session_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_content_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Ręczne doczytanie materiałów z content/ bez restartu aplikacji.
         *
         *     To samo robi lifespan przy starcie; endpoint jest po to, żeby fiszka
         *     dopisana do pliku w trakcie sesji nauki nie wymagała ubijania serwera.
         *     Import jest idempotentny, więc kliknięcie dwa razy nic nie psuje.
         */
        post: operations["sync_api_content_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Cała baza jako jeden plik JSON, gotowy do pobrania.
         */
        get: operations["export_api_backup_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Co wejdzie z pliku - do pokazania PRZED zgodą na skasowanie tego, co jest.
         */
        post: operations["preview_api_backup_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Backup
         * @description Zastępuje całą zawartość bazy danymi z pliku.
         *
         *     Przed nadpisaniem powstaje kopia bezpieczeństwa obok pliku bazy - przez
         *     sqlite3 backup API, nie kopiowanie pliku, bo baza chodzi w trybie WAL
         *     i surowa kopia bez sidecarów potrafi być niespójna.
         */
        post: operations["import_backup_api_backup_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Achievement */
        Achievement: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Hint */
            hint: string;
            /** Icon */
            icon: string;
            /** Unlocked */
            unlocked: boolean;
        };
        /** ActivityEntry */
        ActivityEntry: {
            /** Id */
            id: number;
            /** Occurred At */
            occurred_at: string;
            /** Kind */
            kind: string;
            /** Ref Id */
            ref_id: number | null;
            /** Detail */
            detail: string;
        };
        /** Attempt */
        Attempt: {
            /** Id */
            id: number;
            /** Question Id */
            question_id: number;
            /** Attempted At */
            attempted_at: string;
            /** Solved Independently */
            solved_independently: boolean;
        };
        /** AttemptCreate */
        AttemptCreate: {
            /** Solved Independently */
            solved_independently: boolean;
        };
        /** BackupImportResult */
        BackupImportResult: {
            /** Summary */
            summary: {
                [key: string]: number;
            };
            /** Backup Path */
            backup_path: string;
        };
        /** BackupPreview */
        BackupPreview: {
            /** Summary */
            summary: {
                [key: string]: number;
            };
            /** Exported At */
            exported_at: string | null;
            /** Schema Version */
            schema_version: number | null;
            /** Compatible */
            compatible: boolean;
            /** Problem */
            problem: string | null;
        };
        /** Body_import_backup_api_backup_import_post */
        Body_import_backup_api_backup_import_post: {
            /** File */
            file: string;
        };
        /** Body_preview_api_backup_preview_post */
        Body_preview_api_backup_preview_post: {
            /** File */
            file: string;
        };
        /** BoxCount */
        BoxCount: {
            /** Box */
            box: number;
            /** Count */
            count: number;
        };
        /**
         * Briefing
         * @description Pierwszy krok sesji: co dziś robisz, z czego i który to punkt fazy.
         *
         *     Jeden zagnieżdżony obiekt zamiast trzech luźnych pól, bo front podejmuje
         *     jedną decyzję ("jest odprawa albo jej nie ma") zamiast korelować zadanie
         *     z listą materiałów i licznikiem.
         */
        Briefing: {
            task: components["schemas"]["NextTask"];
            /** Materials */
            materials: components["schemas"]["Resource"][];
            /** Done */
            done: number;
            /** Total */
            total: number;
        };
        /** ContentStatus */
        ContentStatus: {
            /** Available */
            available: {
                [key: string]: number;
            };
            /** Imported */
            imported: {
                [key: string]: number;
            };
        };
        /** ContentSyncResult */
        ContentSyncResult: {
            /** Flashcards Added */
            flashcards_added: number;
            /** Questions Added */
            questions_added: number;
            /** Resources Added */
            resources_added: number;
            /** Tasks Added */
            tasks_added: number;
            /** Answers Filled */
            answers_filled: number;
            /** Skipped */
            skipped: number;
            /** Warnings */
            warnings: string[];
        };
        /** Counter */
        Counter: {
            /** Done */
            done: number;
            /** Total */
            total: number;
            /** Pct */
            pct: number;
        };
        /** Dashboard */
        Dashboard: {
            roadmap: components["schemas"]["Counter"];
            /** Due Count */
            due_count: number;
            /** Intro Count */
            intro_count: number;
            independence: components["schemas"]["Independence"];
            /** Boxes */
            boxes: components["schemas"]["BoxCount"][];
            /** Cards Total */
            cards_total: number;
            next_task: components["schemas"]["NextTask"] | null;
            streak: components["schemas"]["Streak"];
            progression: components["schemas"]["Progression"];
        };
        /** DayNote */
        DayNote: {
            /** Day */
            day: string;
            /** Note */
            note: string;
        };
        /** DayNoteUpdate */
        DayNoteUpdate: {
            /** Note */
            note: string;
        };
        /**
         * DayPhase
         * @description Ile zdarzeń dnia przypadło na tę fazę. None = fazy już nie da się ustalić.
         */
        DayPhase: {
            /** Phase Id */
            phase_id: number | null;
            /** Count */
            count: number;
        };
        /** Flashcard */
        Flashcard: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number | null;
            /** Front */
            front: string;
            /** Back */
            back: string;
            /** Box */
            box: number;
            /** Next Review At */
            next_review_at: string;
            /** Learned At */
            learned_at: string | null;
            /** Own Note */
            own_note: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** FlashcardCreate */
        FlashcardCreate: {
            /** Front */
            front: string;
            /** Back */
            back: string;
            /** Phase Id */
            phase_id?: number | null;
        };
        /** FlashcardUpdate */
        FlashcardUpdate: {
            /** Front */
            front?: string | null;
            /** Back */
            back?: string | null;
            /** Own Note */
            own_note?: string | null;
            /** Phase Id */
            phase_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapDay */
        HeatmapDay: {
            /** Day */
            day: string;
            /** Count */
            count: number;
        };
        /** Independence */
        Independence: {
            /** Independent */
            independent: number;
            /** Total */
            total: number;
            /** Pct */
            pct: number;
        };
        /**
         * JournalDay
         * @description Jeden dzień dziennika - wyliczony, nie przechowywany (poza notatką).
         */
        JournalDay: {
            /** Day */
            day: string;
            /** Events */
            events: number;
            /** Reviewed */
            reviewed: number;
            /** Introduced */
            introduced: number;
            /** Attempts */
            attempts: number;
            /** Independent */
            independent: number;
            /** Tasks Done */
            tasks_done: number;
            /** Resources Done */
            resources_done: number;
            /** Xp */
            xp: number;
            /** Phases */
            phases: components["schemas"]["DayPhase"][];
            /** Note */
            note: string;
        };
        /** NextTask */
        NextTask: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number;
            /** Title */
            title: string;
            /** Phase Name */
            phase_name: string;
            /** Notes */
            notes: string;
        };
        /** Phase */
        Phase: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Order Index */
            order_index: number;
        };
        /** PhaseProgress */
        PhaseProgress: {
            phase: components["schemas"]["Phase"];
            /** Done */
            done: number;
            /** Total */
            total: number;
            /** Pct */
            pct: number;
        };
        /** Progression */
        Progression: {
            /** Xp */
            xp: number;
            /** Level */
            level: number;
            /** Xp Into Level */
            xp_into_level: number;
            /** Xp For Next Level */
            xp_for_next_level: number;
            /** Pct */
            pct: number;
        };
        /** Question */
        Question: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number | null;
            /** Question Text */
            question_text: string;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "concept" | "code";
            /** Answer */
            answer: string;
            /** Created At */
            created_at: string;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Phase Id */
            phase_id: number;
            /** Question Text */
            question_text: string;
            /**
             * Question Type
             * @default concept
             * @enum {string}
             */
            question_type: "concept" | "code";
            /**
             * Answer
             * @default
             */
            answer: string;
        };
        /** QuestionStats */
        QuestionStats: {
            /** Total */
            total: number;
            /** Independent */
            independent: number;
            /** Pct */
            pct: number;
        };
        /** QuestionUpdate */
        QuestionUpdate: {
            /** Question Text */
            question_text?: string | null;
            /** Question Type */
            question_type?: ("concept" | "code") | null;
            /** Answer */
            answer?: string | null;
            /** Phase Id */
            phase_id?: number | null;
        };
        /**
         * QuestionWithStats
         * @description Pytanie razem ze skumulowanym wskaźnikiem samodzielności.
         *
         *     Statystyki w tej samej odpowiedzi, a nie osobnym endpointem per pytanie:
         *     faza z dwunastoma pytaniami dawałaby dwanaście round-tripów, a to już widać
         *     w interfejsie.
         */
        QuestionWithStats: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number | null;
            /** Question Text */
            question_text: string;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "concept" | "code";
            /** Answer */
            answer: string;
            /** Created At */
            created_at: string;
            stats: components["schemas"]["QuestionStats"];
        };
        /** Resource */
        Resource: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
            /**
             * Status
             * @enum {string}
             */
            status: "todo" | "in_progress" | "done";
            /** Order Index */
            order_index: number;
        };
        /** ResourceCreate */
        ResourceCreate: {
            /** Phase Id */
            phase_id?: number | null;
            /** Title */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Kind
             * @default other
             * @enum {string}
             */
            kind: "book" | "course" | "video" | "docs" | "article" | "dataset" | "other";
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ResourceUpdate */
        ResourceUpdate: {
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Detail */
            detail?: string | null;
            /** Status */
            status?: ("todo" | "in_progress" | "done") | null;
            /** Phase Id */
            phase_id?: number | null;
        };
        /** ReviewResult */
        ReviewResult: {
            /** Correct */
            correct: boolean;
        };
        /** SessionPlan */
        SessionPlan: {
            briefing: components["schemas"]["Briefing"] | null;
            /** Intro */
            intro: components["schemas"]["Flashcard"][];
            /** Reviews */
            reviews: components["schemas"]["Flashcard"][];
            /** Reviews Remaining */
            reviews_remaining: number;
            /** Questions */
            questions: components["schemas"]["QuestionWithStats"][];
            phase: components["schemas"]["Phase"] | null;
            next_task: components["schemas"]["NextTask"] | null;
            /** Total Steps */
            total_steps: number;
            /** Estimated Minutes */
            estimated_minutes: number;
        };
        /** Streak */
        Streak: {
            /** Current */
            current: number;
            /** Longest */
            longest: number;
            /** Active Days */
            active_days: number;
        };
        /** Task */
        Task: {
            /** Id */
            id: number;
            /** Phase Id */
            phase_id: number;
            /** Title */
            title: string;
            /** Notes */
            notes: string;
            /** Is Done */
            is_done: boolean;
            /** Order Index */
            order_index: number;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Phase Id */
            phase_id: number;
            /** Title */
            title: string;
        };
        /**
         * TaskUpdate
         * @description PATCH: pominięte pole zostaje bez zmian, w odróżnieniu od pola z null.
         *
         *     Rozróżnienie jest istotne przy `notes`, gdzie pusty string to poprawna
         *     wartość ("wyczyść notatkę"), a brak pola oznacza "nie dotykaj".
         */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
            /** Is Done */
            is_done?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    get_achievements_api_achievements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Achievement"][];
                };
            };
        };
    };
    list_phases_api_phases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhaseProgress"][];
                };
            };
        };
    };
    list_phase_tasks_api_phases__phase_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phase_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flashcards_api_flashcards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"][];
                };
            };
        };
    };
    create_flashcard_api_flashcards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashcardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_due_api_flashcards_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"][];
                };
            };
        };
    };
    list_intro_api_flashcards_intro_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_flashcard_api_flashcards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_flashcard_api_flashcards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashcardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_flashcard_api_flashcards__card_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewResult"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    introduce_flashcard_api_flashcards__card_id__intro_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flashcard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query: {
                phase_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionWithStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_api_questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_attempts_api_questions__question_id__attempts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attempt"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attempt_api_questions__question_id__attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_resources_api_resources_get: {
        parameters: {
            query: {
                phase_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_resource_api_resources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_resource_api_resources__resource_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_resource_api_resources__resource_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resource_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_streak_api_journal_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Streak"];
                };
            };
        };
    };
    get_heatmap_api_journal_heatmap_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_journal_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_days_api_journal_days_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalDay"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_day_note_api_journal_days__day__note_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayNoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayNote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_api_session_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPlan"];
                };
            };
        };
    };
    get_status_api_content_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStatus"];
                };
            };
        };
    };
    sync_api_content_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentSyncResult"];
                };
            };
        };
    };
    export_api_backup_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_api_backup_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_api_backup_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_backup_api_backup_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_backup_api_backup_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
